### ISSUE TITLE
Pneumonia Detector project

### ISSUE THREAD

**Issue by arijitdas123student** [gigwegbe/tinyml-papers-and-projects#1]
Wanna like to add this: [Under $100 and Less Than 1mW: Pneumonia Detection Solution for Everyone](https://www.edgeimpulse.com/blog/under-dollar100-and-less-than-1mw-pneumonia-detection-solution-for-everyone) ? 😄

**Comment by gigwegbe** [comment]
Done. Thanks for sharing your project. 😄
