### ISSUE TITLE
Incorrect link for the 2023 paper 3

### ISSUE THREAD

**Issue by chinya07** [gigwegbe/tinyml-papers-and-projects#17]
The link for the 2023 paper "Faster Attention Is What You Need: A Fast Self-Attention Neural Network Backbone Architecture for the Edge via Double-Condensing Attention Condensers" is incorrect (dead). 

dead link: https://arxiv.org/pdf
correct link: https://arxiv.org/pdf/2208.06980.pdf

**Comment by gigwegbe** [comment]
Thanks @chinya07. I have fixed the dead link.
